---

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

env:
    node: true

parser:
    babel-eslint

parserOptions:
    ecmaVersion: 2017
    sourceType: module

extends:
    - 'airbnb-base'

rules:
    no-console: 0
