---
plugins:
  - import

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - 'airbnb-base'

env:
    node: true

parser:
    babel-eslint

parserOptions:
    ecmaVersion: 2017
    sourceType: module

rules:
    no-console: 0
