---
plugins:
  - import

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - 'airbnb-base'

env:
    node: true

parser:
    babel-eslint

parserOptions:
    ecmaVersion: 2017
    sourceType: module

rules:
    no-console: 0
    import/no-extraneous-dependencies: 2
    import/unambiguous: 1
    import/no-unresolved: 1

settings:
  import/resolver:
    node:
      paths: [ src ]
